import { s } from "vite/dist/node/types.d-FdqQ54oU";

export const puppyEvolutionMap: Record<string, string | null> = {
  puppy: 'dog',
  dog: 'wolf pup',
  'wolf pup': 'wolf',
  wolf: 'dire wolf',
  'dire wolf': 'spirit wolf',
  'spirit wolf': 'shadowfang', 
  shadowfang: 'lupine guardian', 
  'lupine guardian': 'stormhowl',
  'stormhowl': 'frostfang', 
  frostfang: 'moonfang',
  moonfang: 'celestial wolf',
  'celestial wolf': 'hell hound',
  'hell hound': 'inferno beast',
  'inferno beast': 'darkfang',
  'darkfang': 'void wolf',
  'void wolf': 'soulbound beast',
  'soulbound beast': 'lupus titan',
  'lupus titan': 'fenrir',
  fenrir: 'warden of the wilds', 
  'warden of the wilds': 'elder lupine',
  'elder lupine': 'acended howler',
  'acended howler': 'primal alpha',
  'primal alpha': 'stellar fang',
  'stellar fang': 'omega hound',
  'omega hound': 'aetherfang',
  aetherfang: 'legendary guardian',
  'legendary guardian': 'mythic lupine deity',
  'mythic lupine deity': null, // final evolution
};

export const puppyEvolutionLevels: Record<string, number> = {
  puppy: 1,
  dog: 5,
  'wolf pup': 10,
  wolf: 15,
  'dire wolf': 20,
  'spirit wolf': 25,
  shadowfang: 30,
  'lupine guardian': 35,
  stormhowl: 40,
  frostfang: 45,
  moonfang: 50,
  'celestial wolf': 55,
  'hell hound': 60,
  'inferno beast': 65,
  darkfang: 70,
  'void wolf': 75,
  'soulbound beast': 80,
  'lupus titan': 85,
  fenrir: 90,
  'warden of the wilds': 95,
  'elder lupine': 100,
  'acended howler': 105,
  'primal alpha': 110,
  'stellar fang': 115,
  'omega hound': 120,
  aetherfang: 125,
  'legendary guardian': 130,
  'mythic lupine deity': 135, // final evolution
};

export const kittenEvolutionMap: Record<string, string | null> = {
 "kitten": "cat",
  "cat": "lynx cub",
  "lynx cub": "lynx",
  "lynx": "saber cat",
  "saber cat": "ice saber",
  "ice saber": "frost claw",
  "frost claw": "snow leopard",
  "snow leopard": "arctic prowler",
  "arctic prowler": "spirit feline",
  "spirit feline": "shadow panther",
  "shadow panther": "void cat",
  "void cat": "night stalker",
  "night stalker": "dark puma",
  "dark puma": "hellcat",
  "hellcat": "inferno feline",
  "inferno feline": "demon panther",
  "demon panther": "chaos hunter",
  "chaos hunter": "phantom lynx",
  "phantom lynx": "abyss stalker",
  "abyss stalker": "duskclaw",
  "duskclaw": "venom whisker",
  "venom whisker": "nullfang",
  "nullfang": "soul shredder",
  "soul shredder": "lunalurk",
  "lunalurk": "eclipse puma",
  "eclipse puma": "night mauler",
  "night mauler": "voidmane",
  "voidmane": null // Final evolution
};

export const kittenEvolutionLevels: Record<string, number> = {
  "kitten": 1,
  "cat": 5,
  "lynx cub": 10,
  "lynx": 15,
  "saber cat": 20,
  "ice saber": 25,
  "frost claw": 30,
  "snow leopard": 35,
  "arctic prowler": 40,
  "spirit feline": 45,
  "shadow panther": 50,
  "void cat": 55,
  "night stalker": 60,
  "dark puma": 65,
  "hellcat": 70,
  "inferno feline": 75,
  "demon panther": 80,
  "chaos hunter": 85,
  "phantom lynx": 90,
  "abyss stalker": 95,
  "duskclaw": 100,
  "venom whisker": 105,
  "nullfang": 110,
  "soul shredder": 115,
  "lunalurk": 120,
  "eclipse puma": 125,
  "night mauler": 130,
  "voidmane": 135 // Final evolution
};